#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const PACKAGE_ROOT = resolve(dirname(SCRIPT_PATH), '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '../..');
const CONFIG_PATH = join(PACKAGE_ROOT, 'agent-pack.config.json');
const DIST_DIR = join(PACKAGE_ROOT, 'dist');
const BUILD_DIR = join(PACKAGE_ROOT, 'build');
const REVIEWS_DIR = join(PACKAGE_ROOT, 'reviews');
const REGISTRY_PATH = join(REVIEWS_DIR, 'registry.json');

const PACK_ID = 'ujg-agent-pack';
const GENERATED_NOTICE = '<!-- Generated by @openuji/ujg-agent-pack. Do not edit directly. -->';

function normalizeNewlines(value) {
  return value.replace(/\r\n/g, '\n');
}

function readText(path) {
  return normalizeNewlines(readFileSync(path, 'utf8'));
}

function readJson(path) {
  return JSON.parse(readText(path));
}

function sha256(content) {
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

function stableJson(value) {
  return `${JSON.stringify(sortValue(value), null, 2)}\n`;
}

function sortValue(value) {
  if (Array.isArray(value)) return value.map(sortValue);
  if (!value || typeof value !== 'object') return value;

  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => [key, sortValue(item)])
  );
}

function rel(path, from = REPO_ROOT) {
  return relative(from, path);
}

function targetPathParts(target) {
  return target.id.split('/');
}

function targetSlug(target) {
  return target.id.replaceAll('/', '-').replaceAll('.', '-');
}

function skillName(target, skill) {
  return `ujg-${targetSlug(target)}-${skill.nameSuffix}`;
}

function sourcePath(target, skill) {
  return join(PACKAGE_ROOT, 'sources', ...targetPathParts(target), 'skills', skill.key, 'skill.md');
}

function sourceExists(target, skill) {
  return existsSync(sourcePath(target, skill));
}

function publicSpecUrl(target, moduleId) {
  if (!moduleId) return target.publicUrl;
  return `${target.publicUrl}/${moduleId}`;
}

function readPackageMetadata() {
  const pkg = readJson(join(PACKAGE_ROOT, 'package.json'));
  return {
    name: pkg.name,
    version: pkg.version,
  };
}

function readConfig() {
  const config = readJson(CONFIG_PATH);
  if ('skills' in config) {
    throw new Error('agent-pack.config.json must define skills per target, not as a top-level skills list');
  }

  const targetIds = new Set(config.targets.map((target) => target.id));
  const trRoot = resolve(REPO_ROOT, 'specs/tr');

  if (!targetIds.has('ed')) {
    throw new Error('agent-pack.config.json must include the ed target');
  }

  if (existsSync(trRoot)) {
    for (const entry of readdirSync(trRoot, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;

      const targetId = `tr/${entry.name}`;
      if (!targetIds.has(targetId)) {
        throw new Error(`agent-pack.config.json is missing target ${targetId}`);
      }
    }
  }

  for (const target of config.targets) {
    if (!Array.isArray(target.skills)) {
      throw new Error(`agent-pack.config.json target ${target.id} must define a skills array`);
    }
    const allowedSkillKeys = new Set([
      'key',
      'title',
      'scope',
      'nameSuffix',
      'moduleId',
      'description',
      'shortDescription',
      'defaultPrompt',
    ]);
    for (const skill of target.skills) {
      const unsupportedKeys = Object.keys(skill).filter((key) => !allowedSkillKeys.has(key));
      if (unsupportedKeys.length > 0) {
        throw new Error(`Skill ${skill.key} contains unsupported config keys: ${unsupportedKeys.join(', ')}`);
      }
    }

    target.specRootAbs = resolve(PACKAGE_ROOT, target.specRoot);
    if (!existsSync(target.specRootAbs)) {
      throw new Error(`Configured spec root does not exist: ${target.specRoot}`);
    }
  }

  return config;
}

function listFiles(directory, options = {}) {
  const files = [];
  const skipNames = new Set(options.skipNames || []);

  function visit(current) {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      if (skipNames.has(entry.name)) continue;

      const path = join(current, entry.name);
      if (entry.isDirectory()) {
        visit(path);
      } else if (entry.isFile()) {
        files.push(path);
      }
    }
  }

  if (existsSync(directory)) visit(directory);
  return files.sort((left, right) => left.localeCompare(right));
}

function hashFiles(root, files) {
  const hash = createHash('sha256');

  for (const file of files) {
    hash.update(relative(root, file));
    hash.update('\0');
    hash.update(readFileSync(file));
    hash.update('\0');
  }

  return `sha256:${hash.digest('hex')}`;
}

function collectSpecModules(target) {
  const modules = new Map();

  function visit(directory) {
    const configPath = join(directory, 'config.json');
    if (existsSync(configPath)) {
      const config = readJson(configPath);
      const id = config.id || relative(target.specRootAbs, directory);
      const files = listFiles(directory, { skipNames: ['content-manifest.json'] });

      modules.set(id, {
        id,
        title: config.title || id,
        directory,
        relativeDirectory: rel(directory),
        deps: Array.isArray(config.deps) ? config.deps : [],
        family: config.custom?.family,
        order: config.custom?.order ?? 999,
        config,
        files: files.map((file) => rel(file)),
        interestingFiles: files
          .filter((file) => /\.(context\.jsonld|shape\.ttl|ttl|json|md)$/.test(file))
          .map((file) => rel(file)),
        hash: hashFiles(directory, files),
      });

      return;
    }

    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (entry.isDirectory()) visit(join(directory, entry.name));
    }
  }

  visit(target.specRootAbs);
  return modules;
}

function sortedModuleIds(modules, ids) {
  return [...new Set(ids)].sort((left, right) => {
    const leftModule = modules.get(left);
    const rightModule = modules.get(right);
    const order = (leftModule?.order ?? 999) - (rightModule?.order ?? 999);
    return order || left.localeCompare(right);
  });
}

function dependencyClosure(modules, moduleId) {
  const seen = new Set();

  function visit(id) {
    if (!id || seen.has(id)) return;
    seen.add(id);

    const module = modules.get(id);
    if (!module) return;
    for (const dep of module.deps) visit(dep);
  }

  visit(moduleId);
  return sortedModuleIds(modules, seen);
}

function dependentClosure(modules, moduleId) {
  const dependents = [];

  for (const id of modules.keys()) {
    if (id === moduleId) continue;
    if (dependencyClosure(modules, id).includes(moduleId)) dependents.push(id);
  }

  return sortedModuleIds(modules, dependents);
}

function buildTargetContext(config, target) {
  const modules = collectSpecModules(target);
  const skills = target.skills
    .filter((skill) => sourceExists(target, skill))
    .map((skill) => {
      const name = skillName(target, skill);
      const source = sourcePath(target, skill);

      return {
        ...skill,
        name,
        displayName: `UJG ${target.shortLabel} ${skill.title}`,
        source,
        sourceRelativePath: rel(source, PACKAGE_ROOT),
        publicUrl: publicSpecUrl(target, skill.moduleId),
      };
    });

  return {
    target,
    modules,
    skills,
  };
}

function buildAllContexts(config) {
  return config.targets.map((target) => buildTargetContext(config, target));
}

function skillModuleIds(context, skill) {
  return skill.moduleId
    ? dependencyClosure(context.modules, skill.moduleId)
    : sortedModuleIds(context.modules, context.modules.keys());
}

function sourceHash(skill) {
  return sha256(readText(skill.source));
}

function specHashInput(context, skill) {
  return Object.fromEntries(
    skillModuleIds(context, skill).map((id) => {
      const module = context.modules.get(id);
      return [id, module?.hash || 'missing'];
    })
  );
}

function specHash(context, skill) {
  return sha256(stableJson(specHashInput(context, skill)));
}

function agentPath(context, skill) {
  return join(BUILD_DIR, 'agents', ...targetPathParts(context.target), skill.key, 'AGENTS.md');
}

function formatSkillRoot(format, skill) {
  return join(BUILD_DIR, format.dir, skill.name);
}

function formatSkillPaths(format, skill) {
  const root = formatSkillRoot(format, skill);

  return {
    root,
    skill: join(root, 'SKILL.md'),
    skillTree: join(root, 'references', 'skill-tree.json'),
    relatedSkills: join(root, 'references', 'related-skills.md'),
    packageState: join(root, 'references', 'package-state.json'),
  };
}

function generatedDescription(context, skill) {
  if (skill.description) return skill.description;

  if (skill.key === 'root') {
    if (context.target.kind === 'ed') {
      return `Generate, review, correct, and reason about User Journey Graph JSON-LD for the ${context.target.label}. Use when modeling UJG documents, checking vocabulary discipline, selecting modules, or correcting Core/Graph/Surface/Runtime/Mapping/Metrics/Experience/Localization/Observability and optional module separation, including Entry Binding, Design System, Data Contract, Effect, Condition, Artifact, and the Domain Model Document Extension.`;
    }

    return `Generate, review, correct, and reason about User Journey Graph JSON-LD for the ${context.target.label}. Use when modeling UJG documents, checking vocabulary discipline, selecting modules, or correcting module boundaries for this target.`;
  }

  return `Generate, review, correct, and reason about ${skill.title} in User Journey Graph JSON-LD for the ${context.target.label}. Use when the task is scoped to ${skill.scope} or when whole-document modeling crosses this module boundary.`;
}

function shortDescription(context, skill) {
  if (skill.shortDescription) return skill.shortDescription;
  if (skill.key === 'root') return `Model UJG JSON-LD for ${context.target.shortLabel}`;
  return `Model UJG ${skill.title.replace(' Modeling', '')} for ${context.target.shortLabel}`;
}

function defaultPrompt(skill) {
  if (skill.defaultPrompt) return skill.defaultPrompt;
  return `Use $${skill.name} to generate or review UJG JSON-LD for this target and scope.`;
}

function yamlString(value) {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function skillsForModule(context, moduleId) {
  return context.skills.filter((skill) => skill.moduleId === moduleId);
}

function generatedSkillTree(context, currentSkill) {
  const moduleGraph = Object.fromEntries(
    [...context.modules.values()]
      .sort((left, right) => left.id.localeCompare(right.id))
      .map((module) => {
        const generatedSkills = skillsForModule(context, module.id).map((skill) => skill.name);

        return [
          module.id,
          {
            title: module.title,
            deps: module.deps,
            dependents: dependentClosure(context.modules, module.id),
            generatedSkill: generatedSkills[0] || null,
            generatedSkills,
          },
        ];
      })
  );

  return {
    target: {
      id: context.target.id,
      label: context.target.label,
      publicUrl: context.target.publicUrl,
      specRoot: rel(context.target.specRootAbs),
    },
    currentSkill: {
      key: currentSkill.key,
      name: currentSkill.name,
      moduleId: currentSkill.moduleId,
      scope: currentSkill.scope,
      publicUrl: currentSkill.publicUrl,
    },
    skills: context.skills.map((skill) => ({
      key: skill.key,
      name: skill.name,
      moduleId: skill.moduleId,
      scope: skill.scope,
      publicUrl: skill.publicUrl,
      source: skill.sourceRelativePath,
    })),
    moduleGraph,
  };
}

function relatedSkills(context, currentSkill) {
  if (currentSkill.key === 'root') {
    return context.skills.filter((skill) => skill.key !== 'root');
  }

  const relatedNames = new Set(['root']);
  for (const moduleId of skillModuleIds(context, currentSkill)) {
    for (const skill of skillsForModule(context, moduleId)) {
      relatedNames.add(skill.key);
    }
  }

  if (currentSkill.moduleId) {
    for (const moduleId of dependentClosure(context.modules, currentSkill.moduleId)) {
      for (const skill of skillsForModule(context, moduleId)) {
        relatedNames.add(skill.key);
      }
    }
  }

  relatedNames.delete(currentSkill.key);
  return context.skills.filter((skill) => relatedNames.has(skill.key));
}

function relatedSkillsMarkdown(context, currentSkill) {
  const related = relatedSkills(context, currentSkill);
  const downstreamModules = currentSkill.moduleId
    ? dependentClosure(context.modules, currentSkill.moduleId)
    : [];

  return `${GENERATED_NOTICE}

# Related Skills

Target: ${context.target.label}
Current skill: ${currentSkill.name}
Module scope: ${currentSkill.moduleId || 'whole target'}

## Sibling Skills

${related.length > 0 ? related.map((skill) => `- ${skill.name}: ${skill.scope}`).join('\n') : '- None'}

## Downstream Spec Modules

${downstreamModules.length > 0 ? downstreamModules.map((id) => `- ${id}`).join('\n') : '- None'}

## Usage

Consult this reference when a task crosses module boundaries. Prefer the most specific generated skill for the module that owns the requested semantics, then return to the root skill for whole-document integration.
`;
}

function skillTreeContextMarkdown(context, skill) {
  const related = relatedSkills(context, skill);

  return `## Skill tree context

Target: ${context.target.label}
Public spec URL: ${context.target.publicUrl}
Scope: ${skill.scope}
Module scope: ${skill.moduleId || 'whole target'}

Related generated skills:
${related.length > 0 ? related.map((item) => `- ${item.name}: ${item.scope}`).join('\n') : '- None'}

When the task crosses module boundaries, read \`references/related-skills.md\` and \`references/skill-tree.json\` before continuing.
`;
}

function buildSkillMarkdown(context, skill) {
  return `---
name: ${skill.name}
description: ${yamlString(generatedDescription(context, skill))}
---

${GENERATED_NOTICE}

# ${skill.displayName}

${skillTreeContextMarkdown(context, skill)}

${readText(skill.source).trim()}
`;
}

function buildAgentsInstructions(context, skill) {
  return `${GENERATED_NOTICE}

# ${skill.displayName} Agent Instructions

Use these instructions for ${skill.scope} in ${context.target.label}.

${skillTreeContextMarkdown(context, skill)}

${readText(skill.source).trim()}
`;
}

function buildOpenAiYaml(context, skill) {
  return `interface:
  display_name: ${yamlString(skill.displayName)}
  short_description: ${yamlString(shortDescription(context, skill))}
  default_prompt: ${yamlString(defaultPrompt(skill))}
`;
}

function homeDir() {
  if (!process.env.HOME) throw new Error('Cannot resolve skills home because HOME is unset');
  return process.env.HOME;
}

const FORMATS = {
  codex: {
    key: 'codex',
    label: 'Codex',
    dir: 'codex',
    extraArtifacts: (context, skill) => [['agents/openai.yaml', buildOpenAiYaml(context, skill)]],
    allowProject: false,
    skillsRoot: () => join(process.env.CODEX_HOME || join(homeDir(), '.codex'), 'skills'),
  },
  claude: {
    key: 'claude',
    label: 'Claude',
    dir: 'claude',
    extraArtifacts: () => [],
    allowProject: true,
    skillsRoot: (options) =>
      options.project
        ? join(resolve(options.project), '.claude', 'skills')
        : join(process.env.CLAUDE_CONFIG_DIR || join(homeDir(), '.claude'), 'skills'),
  },
};

function artifactContents(format, context, skill) {
  return [
    ['SKILL.md', buildSkillMarkdown(context, skill)],
    ...format.extraArtifacts(context, skill),
    ['references/skill-tree.json', stableJson(generatedSkillTree(context, skill))],
    ['references/related-skills.md', relatedSkillsMarkdown(context, skill)],
  ];
}

function artifactHash(entries) {
  const hash = createHash('sha256');

  for (const [path, content] of entries) {
    hash.update(path);
    hash.update('\0');
    hash.update(content);
    hash.update('\0');
  }

  return `sha256:${hash.digest('hex')}`;
}

function configHash() {
  return sha256(readText(CONFIG_PATH));
}

function buildPackageState(format, context, skill) {
  const metadata = readPackageMetadata();

  return stableJson({
    package: {
      id: PACK_ID,
      name: metadata.name,
      version: metadata.version,
    },
    target: {
      id: context.target.id,
      label: context.target.label,
    },
    skill: {
      key: skill.key,
      name: skill.name,
      moduleId: skill.moduleId,
    },
    sourceHash: sourceHash(skill),
    specHash: specHash(context, skill),
    configHash: configHash(),
    artifactHash: artifactHash(artifactContents(format, context, skill)),
  });
}

function buildManifest(contexts, outputs) {
  const metadata = readPackageMetadata();

  return stableJson({
    id: PACK_ID,
    name: metadata.name,
    version: metadata.version,
    config: {
      path: 'agent-pack.config.json',
      hash: configHash(),
    },
    targets: contexts.map((context) => ({
      id: context.target.id,
      label: context.target.label,
      publicUrl: context.target.publicUrl,
      specRoot: rel(context.target.specRootAbs),
      skills: context.skills.map((skill) => ({
        key: skill.key,
        name: skill.name,
        moduleId: skill.moduleId,
        source: skill.sourceRelativePath,
        sourceHash: sourceHash(skill),
        specHash: specHash(context, skill),
        artifactHash: artifactHash(artifactContents(FORMATS.codex, context, skill)),
        claudeArtifactHash: artifactHash(artifactContents(FORMATS.claude, context, skill)),
      })),
    })),
    generatedFiles: [...outputs.keys()].map((path) => rel(path, BUILD_DIR)).sort(),
  });
}

function buildOutputs() {
  const config = readConfig();
  const contexts = buildAllContexts(config);
  const outputs = new Map();

  for (const context of contexts) {
    for (const skill of context.skills) {
      outputs.set(agentPath(context, skill), buildAgentsInstructions(context, skill));

      for (const format of Object.values(FORMATS)) {
        const root = formatSkillRoot(format, skill);
        for (const [path, content] of artifactContents(format, context, skill)) {
          outputs.set(join(root, path), content);
        }
        outputs.set(formatSkillPaths(format, skill).packageState, buildPackageState(format, context, skill));
      }
    }
  }

  outputs.set(join(BUILD_DIR, 'manifest.json'), buildManifest(contexts, outputs));
  return { contexts, outputs };
}

function generateOutputs() {
  const { outputs } = buildOutputs();
  rmSync(BUILD_DIR, { recursive: true, force: true });

  for (const [path, content] of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
  }

  console.log(`Generated ${outputs.size} files in ${rel(BUILD_DIR)}`);
}

function parseSkillFrontmatter(path, content) {
  if (!content.startsWith('---\n')) {
    throw new Error(`${rel(path)}: missing YAML frontmatter`);
  }

  const end = content.indexOf('\n---\n', 4);
  if (end === -1) {
    throw new Error(`${rel(path)}: unterminated YAML frontmatter`);
  }

  const frontmatterLines = content.slice(4, end).split('\n');
  const frontmatter = new Map();

  for (const line of frontmatterLines) {
    const match = /^([a-z][a-z0-9-]*):\s*(.*)$/.exec(line);
    if (!match) {
      throw new Error(`${rel(path)}: invalid frontmatter line "${line}"`);
    }
    frontmatter.set(match[1], match[2]);
  }

  return {
    frontmatter,
    body: content.slice(end + '\n---\n'.length),
  };
}

function unquoteYamlString(value) {
  if (value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  }

  return value;
}

const MAX_SKILL_NAME_LENGTH = 64;
const MAX_SKILL_DESCRIPTION_LENGTH = 1024;

function validateFormatSkill(format, skill, outputs) {
  const path = formatSkillPaths(format, skill).skill;
  const errors = [];

  try {
    const { frontmatter, body } = parseSkillFrontmatter(path, outputs.get(path));
    const keys = [...frontmatter.keys()];
    const name = frontmatter.get('name') || '';
    const description = unquoteYamlString(frontmatter.get('description') || '');

    if (keys.join(',') !== 'name,description') {
      errors.push(`${rel(path)}: frontmatter must contain only name and description`);
    }
    if (!/^[a-z0-9-]+$/.test(name)) {
      errors.push(`${rel(path)}: name must use lowercase letters, digits, and hyphens only`);
    }
    if (name.length > MAX_SKILL_NAME_LENGTH) {
      errors.push(`${rel(path)}: name must be at most ${MAX_SKILL_NAME_LENGTH} characters`);
    }
    if (description.length === 0) {
      errors.push(`${rel(path)}: description must not be empty`);
    }
    if (description.length > MAX_SKILL_DESCRIPTION_LENGTH) {
      errors.push(`${rel(path)}: description must be at most ${MAX_SKILL_DESCRIPTION_LENGTH} characters`);
    }
    if (/[<>]/.test(description)) {
      errors.push(`${rel(path)}: description must not contain angle brackets`);
    }
    if (body.trim().length === 0) {
      errors.push(`${rel(path)}: body must not be empty`);
    }
  } catch (error) {
    errors.push(error.message);
  }

  return errors;
}

function validateGeneratedArtifacts() {
  const { contexts, outputs } = buildOutputs();
  const errors = [];

  for (const context of contexts) {
    for (const skill of context.skills) {
      for (const format of Object.values(FORMATS)) {
        errors.push(...validateFormatSkill(format, skill, outputs));
      }
    }
  }

  if (errors.length > 0) {
    for (const error of errors) console.error(error);
    process.exitCode = 1;
    return;
  }

  console.log('UJG agent pack skills are valid');
}

function checkPack() {
  validateGeneratedArtifacts();
  if (!process.exitCode) checkReviews();
}

function reviewKey(context, skill) {
  return `${context.target.id}/${skill.key}`;
}

function reviewPath(context, skill) {
  return join(REVIEWS_DIR, ...targetPathParts(context.target), skill.key, 'latest.md');
}

function readRegistry() {
  if (!existsSync(REGISTRY_PATH)) return { version: 1, entries: {} };
  return readJson(REGISTRY_PATH);
}

function writeRegistry(registry) {
  mkdirSync(dirname(REGISTRY_PATH), { recursive: true });
  writeFileSync(REGISTRY_PATH, stableJson(registry), 'utf8');
}

function currentReviewState(context, skill) {
  return {
    target: context.target.id,
    skill: skill.key,
    sourceHash: sourceHash(skill),
    specHash: specHash(context, skill),
    reportPath: rel(reviewPath(context, skill), PACKAGE_ROOT),
  };
}

function sourceHeadings(skill) {
  return readText(skill.source)
    .split('\n')
    .filter((line) => /^#{1,3}\s+/.test(line))
    .map((line) => line.replace(/^#{1,3}\s+/, '').trim());
}

function likelyAffectedHeadings(skill) {
  const headings = sourceHeadings(skill);
  const tokens = new Set([skill.key, skill.moduleId, skill.title].filter(Boolean).map((value) => value.toLowerCase()));

  const matches = headings.filter((heading) => {
    const lower = heading.toLowerCase();
    return [...tokens].some((token) => token && lower.includes(token));
  });

  return matches.length > 0 ? matches : headings.slice(0, 12);
}

function buildReviewReport(context, skill, previous) {
  const current = currentReviewState(context, skill);
  const sourceChanged = !previous || previous.sourceHash !== current.sourceHash;
  const specChanged = !previous || previous.specHash !== current.specHash;
  const headings = likelyAffectedHeadings(skill);

  return `# Skill Review: ${skill.name}

Target: ${context.target.label}
Skill scope: ${skill.scope}
Source: ${skill.sourceRelativePath}
Spec URL: ${skill.publicUrl}

## Status

${previous ? '- Previous review state found.' : '- No previous accepted review state found.'}
- ${sourceChanged || specChanged ? 'Review is required before check can pass.' : 'Source and spec hashes are unchanged.'}

## Review Inputs

- Source hash: ${current.sourceHash}
- Spec hash: ${current.specHash}

## Source Headings Likely Affected

${headings.length > 0 ? headings.map((heading) => `- ${heading}`).join('\n') : '- None'}

## Checklist

- Confirm source guidance still matches the current spec module definitions.
- Confirm cross-skill dependencies still route work to the right sibling skill.
- Update source skill text if the spec changed semantics, terms, constraints, or boundaries.
- Run \`pnpm agent-pack:generate\` to inspect generated skills under \`build/\`.
- Accept the review only after the source matches the current spec.
`;
}

function parseOptions(args) {
  const options = { unknown: [] };
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--') {
      continue;
    } else if (arg === '--target') {
      options.target = args[index + 1];
      index += 1;
    } else if (arg === '--skill') {
      options.skill = args[index + 1];
      index += 1;
    } else if (arg === '--project') {
      options.project = args[index + 1];
      index += 1;
    } else {
      options.unknown.push(arg);
    }
  }
  return options;
}

function filteredContextSkills(options = {}) {
  const config = readConfig();
  const contexts = buildAllContexts(config);
  const pairs = [];

  for (const context of contexts) {
    if (options.target && context.target.id !== options.target) continue;
    for (const skill of context.skills) {
      if (options.skill && skill.key !== options.skill) continue;
      pairs.push({ context, skill });
    }
  }

  if (pairs.length === 0) {
    throw new Error(`No generated skills match ${JSON.stringify(options)}`);
  }

  return pairs;
}

function writeReviewReports(options = {}) {
  const registry = readRegistry();

  for (const { context, skill } of filteredContextSkills(options)) {
    const key = reviewKey(context, skill);
    const path = reviewPath(context, skill);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, buildReviewReport(context, skill, registry.entries[key]), 'utf8');
    console.log(`Reviewed ${key}: ${rel(path)}`);
  }
}

function checkReviews(options = {}) {
  const registry = readRegistry();
  const errors = [];

  for (const { context, skill } of filteredContextSkills(options)) {
    const key = reviewKey(context, skill);
    const current = currentReviewState(context, skill);
    const accepted = registry.entries[key];

    if (!accepted) {
      errors.push(`${key} has not been accepted; run pnpm agent-pack:review and pnpm agent-pack:review:accept -- --target ${context.target.id} --skill ${skill.key}`);
      continue;
    }

    if (accepted.sourceHash !== current.sourceHash) {
      errors.push(`${key} source changed since review acceptance`);
    }
    if (accepted.specHash !== current.specHash) {
      errors.push(`${key} relevant spec modules changed since review acceptance`);
    }
  }

  if (errors.length > 0) {
    for (const error of errors) console.error(error);
    process.exitCode = 1;
    return;
  }

  console.log('UJG agent pack skill reviews are current');
}

function acceptReviews(options = {}) {
  const registry = readRegistry();
  registry.entries ||= {};
  const pairs = filteredContextSkills(options);
  const selectedKeys = new Set(pairs.map(({ context, skill }) => reviewKey(context, skill)));

  if (!options.skill) {
    for (const [key, entry] of Object.entries(registry.entries)) {
      if (options.target && entry.target !== options.target) continue;
      if (!selectedKeys.has(key)) delete registry.entries[key];
    }
  }

  for (const { context, skill } of pairs) {
    const key = reviewKey(context, skill);
    const current = currentReviewState(context, skill);
    const path = reviewPath(context, skill);

    registry.entries[key] = current;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, buildReviewReport(context, skill, registry.entries[key]), 'utf8');
    console.log(`Accepted ${key}`);
  }

  writeRegistry(registry);
}

function installSkill(skillsRoot, format, skill) {
  const source = formatSkillRoot(format, skill);
  const target = join(skillsRoot, skill.name);
  rmSync(target, { recursive: true, force: true });
  mkdirSync(dirname(target), { recursive: true });
  cpSync(source, target, { recursive: true });
  console.log(`Installed ${skill.name} to ${target}`);
}

function cleanStaleTargetSkills(skillsRoot, targetId, currentSkillNames) {
  if (!existsSync(skillsRoot)) return;

  for (const entry of readdirSync(skillsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || currentSkillNames.has(entry.name)) continue;

    const skillRoot = join(skillsRoot, entry.name);
    const statePath = join(skillRoot, 'references', 'package-state.json');
    if (!existsSync(statePath)) continue;

    try {
      const state = readJson(statePath);
      if (state.package?.id === PACK_ID && state.target?.id === targetId) {
        rmSync(skillRoot, { recursive: true, force: true });
        console.log(`Removed stale ${entry.name} from ${skillRoot}`);
      }
    } catch {
      // Ignore malformed state files; install should not remove ambiguous local data.
    }
  }
}

function resolveInstallPairs(format, options = {}) {
  if (options.skill || options.unknown?.length > 0) {
    throw new Error(`${format.label} install supports target-level installs only: use install ${format.key} --target <id>`);
  }

  if (options.project && !format.allowProject) {
    throw new Error(`${format.label} install does not support --project`);
  }

  if (!options.target) {
    throw new Error(`${format.label} install requires --target <id>`);
  }

  const { contexts } = buildOutputs();
  const selected = contexts
    .filter((context) => context.target.id === options.target)
    .flatMap((context) => context.skills.map((skill) => ({ context, skill })));

  if (selected.length === 0) {
    throw new Error(`No generated skills match target ${options.target}`);
  }

  return selected;
}

function installSkills(formatKey, options = {}) {
  const format = FORMATS[formatKey];
  const pairs = resolveInstallPairs(format, options);
  const skillsRoot = format.skillsRoot(options);

  checkPack();
  if (process.exitCode) {
    throw new Error('Cannot install while validation fails or reviews are stale');
  }

  generateOutputs();
  cleanStaleTargetSkills(
    skillsRoot,
    options.target,
    new Set(pairs.map(({ skill }) => skill.name))
  );

  for (const { skill } of pairs) {
    installSkill(skillsRoot, format, skill);
  }
}

function packArtifact() {
  checkPack();
  if (process.exitCode) return;

  generateOutputs();

  const metadata = readPackageMetadata();
  rmSync(DIST_DIR, { recursive: true, force: true });
  mkdirSync(DIST_DIR, { recursive: true });

  const archiveName = `${PACK_ID}-${metadata.version}.tar.gz`;
  const archivePath = join(DIST_DIR, archiveName);

  execFileSync(
    'tar',
    [
      '-czf',
      archivePath,
      'README.md',
      'agent-pack.config.json',
      'build',
      'package.json',
      'reviews',
      'scripts/agent-pack.js',
      'sources',
    ],
    { cwd: PACKAGE_ROOT, stdio: 'inherit' }
  );

  console.log(`Packed ${rel(archivePath)}`);
}

function printUsage() {
  console.error(`Usage:
  ujg-agent-pack generate
  ujg-agent-pack check
  ujg-agent-pack validate
  ujg-agent-pack review [--target <id>] [--skill <key>]
  ujg-agent-pack review check [--target <id>] [--skill <key>]
  ujg-agent-pack review accept [--target <id>] [--skill <key>]
  ujg-agent-pack install codex --target <id>
  ujg-agent-pack install claude --target <id> [--project <dir>]
  ujg-agent-pack pack`);
}

function main() {
  const [command, subcommand, ...rest] = process.argv.slice(2);

  try {
    if (command === 'generate') {
      generateOutputs();
    } else if (command === 'check') {
      checkPack();
    } else if (command === 'validate') {
      validateGeneratedArtifacts();
    } else if (command === 'review' && subcommand === 'check') {
      checkReviews(parseOptions(rest));
    } else if (command === 'review' && subcommand === 'accept') {
      acceptReviews(parseOptions(rest));
    } else if (command === 'review') {
      writeReviewReports(parseOptions([subcommand, ...rest].filter(Boolean)));
    } else if (command === 'install' && Object.hasOwn(FORMATS, subcommand)) {
      installSkills(subcommand, parseOptions(rest));
    } else if (command === 'pack') {
      packArtifact();
    } else {
      printUsage();
      process.exitCode = 1;
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

main();
