name: "Use case"
description: "Propose a real-world use case UJG should cover"
title: "[Use case] <short name>"
labels:
  - "use-case"
  - "needs-triage"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping UJG! If you want to follow discussions and calls, join the W3C UJG Community Group (link in the sidebar / README).

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "One sentence — what user goal/journey is this about?"
      placeholder: "A user compares plans and upgrades without losing context."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Product domain + why this matters."
      placeholder: "Subscription SaaS; users churn when upgrade flow is confusing."
    validations:
      required: true

  - type: textarea
    id: actors
    attributes:
      label: "Actors / personas"
      placeholder: "New user, returning user, admin, support agent…"

  - type: textarea
    id: journey
    attributes:
      label: "Journey narrative (steps)"
      description: "Write it as a short story, not screens."
      placeholder: |
        1) User starts on pricing page...
        2) Compares options...
        3) Hits a blocker...
        4) Resolves and completes...
    validations:
      required: true

  - type: textarea
    id: success
    attributes:
      label: "Success criteria"
      placeholder: "User completes upgrade in <2 min; no dead-ends; clear confirmation."

  - type: textarea
    id: failure
    attributes:
      label: "Failure modes / edge cases"
      placeholder: "Auth expires, payment fails, user changes device, accessibility needs..."

  - type: textarea
    id: signals
    attributes:
      label: "Measurement signals (optional)"
      description: "What would you instrument to know it works?"
      placeholder: "Drop-off points, loops, time-to-complete, recovery rate…"

  - type: checkboxes
    id: checklist
    attributes:
      label: "Contribution checklist"
      options:
        - label: "I checked for duplicates"
          required: true
        - label: "I can clarify details if maintainers ask follow-ups"
          required: true
        - label: "I want updates via the W3C CG (mailing list / calls)"
          required: false
